- type: replace
  path: /instance_groups/name=log-api/jobs/name=loggregator_trafficcontroller/properties/loggregator/outgoing_cert?
  value: "((loggregator_trafficcontroller_tls.certificate))"

- type: replace
  path: /instance_groups/name=log-api/jobs/name=loggregator_trafficcontroller/properties/loggregator/outgoing_key?
  value: "((loggregator_trafficcontroller_tls.private_key))"

- type: replace
  path: /variables/name=loggregator_trafficcontroller_tls?
  value:
    name: loggregator_trafficcontroller_tls
    type: certificate
    options:
      alternative_names:
        - doppler.((system_domain))
        - log-api.service.cf.internal
      ca: service_cf_internal_ca
      common_name: doppler.((system_domain))

- type: replace
  path: /instance_groups/name=log-api/jobs/name=route_registrar/properties/route_registrar/routes/name=doppler?
  value:
    name: doppler
    tls_port: 8081
    registration_interval: 20s
    server_cert_domain_san: doppler.((system_domain))
    uris:
      - doppler.((system_domain))
      - '*.doppler.((system_domain))'