---
- type: replace
  path: /instance_groups/name=log-api/jobs/name=reverse_log_proxy_gateway/properties/metrics?
  value:
    ca_cert: "((rlp_gateway_metrics_tls.ca))"
    cert: "((rlp_gateway_metrics_tls.certificate))"
    key: "((rlp_gateway_metrics_tls.private_key))"
    server_name: rlp_gateway_metrics

- type: replace
  path: /variables/name=metric_scraper_ca?
  value:
    name: metric_scraper_ca
    type: certificate
    options:
      is_ca: true
      common_name: metricScraperCA

- type: replace
  path: /variables/name=rlp_gateway_metrics_tls?
  value:
    name: rlp_gateway_metrics_tls
    type: certificate
    options:
      ca: metric_scraper_ca
      common_name: rlp_gateway_metrics
      extended_key_usage:
      - server_auth
