name: loggregator

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

addons:
- name: bpm
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bpm
    release: bpm

releases:
- name: loggregator
  version: latest
- name: "log-cache"
  version: "1.4.3"
  url: "https://bosh.io/d/github.com/cloudfoundry/log-cache-release?v=1.4.3"
  sha1: "0bea8311d021ca40daee57edf109d5ded863d658"
- name: "bpm"
  version: "0.12.3"
  url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.12.3"
  sha1: "313664d2e6d8485ffa0683979a401f7722f63a50"
- name: "loggregator-agent"
  version: "2.3"
  url: "https://bosh.io/d/github.com/cloudfoundry/loggregator-agent-release?v=2.3"
  sha1: "7532818b5d518b87b57cf36ddc2bf81758f606f9"

instance_groups:
- name: log-cache
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: log-cache-group-reader
    properties:
      port: 8084
    release: log-cache
  - name: log-cache-scheduler
    release: log-cache
  - name: log-cache
    provides:
      log-cache: {shared: true}
    properties:
      egress_port: 8080
      health_addr: localhost:6060
      tls:
        ca_cert: ((log_cache.ca))
        cert: ((log_cache.certificate))
        key: ((log_cache.private_key))
    release: log-cache
  - consumes:
      reverse_log_proxy:
        from: reverse_log_proxy
    name: log-cache-nozzle
    properties:
      logs_provider:
        tls:
          ca_cert: ((logs_provider.ca))
          cert: ((logs_provider.certificate))
          key: ((logs_provider.private_key))
    release: log-cache
- name: doppler
  azs:
  - z1
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
   - name: doppler
     release: loggregator
     provides:
       doppler: {as: doppler, shared: true}
       loggregator: {as: loggregator, shared: true}
     properties:
       doppler:
         disable_announce: true
         syslog_skip_cert_verify: true
       loggregator:
         disable_syslog_drains: true
         tls:
           ca_cert: "((loggregator_router.ca))"
           doppler:
             cert: "((loggregator_router.certificate))"
             key: "((loggregator_router.private_key))"
   - name: loggregator_agent
     release: loggregator-agent
     properties: &agent_properties
       disable_udp: false
       deployment: loggregator
       bosh_dns: true
       doppler:
         addr: ~
       loggregator:
         tls:
           ca_cert: "((loggregator_agent.ca))"
           agent:
             cert: "((loggregator_agent.certificate))"
             key: "((loggregator_agent.private_key))"

- name: log-api
  azs:
  - z1
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: reverse_log_proxy
    release: loggregator
    provides:
      reverse_log_proxy: {as: reverse_log_proxy, shared: true}
    properties:
      loggregator:
        tls:
          ca_cert: "((loggregator_rlp.ca))"
          reverse_log_proxy:
            cert: "((loggregator_rlp.certificate))"
            key: "((loggregator_rlp.private_key))"
  - name: reverse_log_proxy_gateway
    release: loggregator
    provides:
      log_gateway: {as: log_gateway, shared: true}
    properties:
      logs_provider:
        ca_cert: "((loggregator_rlp_gateway.ca))"
        client_cert: "((loggregator_rlp_gateway.certificate))"
        client_key: "((loggregator_rlp_gateway.private_key))"
  - name: loggregator_trafficcontroller
    release: loggregator
    provides:
      trafficcontroller: {as: trafficcontroller, shared: true}
    properties:
      cc:
        internal_service_hostname: ""
        tls_port: 0
        mutual_tls:
          ca_cert: "((loggregator_tc.ca))"
      uaa:
        url: ""
      system_domain: unused
      traffic_controller:
        disable_access_control: true
      loggregator:
        tls:
          ca_cert: "((loggregator_tc.ca))"
          trafficcontroller:
            cert: "((loggregator_tc.certificate))"
            key: "((loggregator_tc.private_key))"
          cc_trafficcontroller:
            cert: "((loggregator_tc.certificate))"
            key: "((loggregator_tc.private_key))"
        uaa:
          client_secret: "some-secret"
      logcache:
        tls:
          ca_cert: "((logcache_trafficcontroller.ca))"
          cert: "((logcache_trafficcontroller.certificate))"
          key: "((logcache_trafficcontroller.private_key))"
      ssl:
        skip_cert_verify: false
  - name: loggregator_agent
    release: loggregator-agent
    properties: *agent_properties
  update:
    max_in_flight: 1
    serial: true

variables:
- name: loggregator_ca
  type: certificate
  options:
    common_name: loggregatorCA
    is_ca: true
- name: loggregator_router
  type: certificate
  options:
    ca: loggregator_ca
    common_name: router
    alternative_names:
    - router
    - doppler
    extended_key_usage:
    - client_auth
    - server_auth
- name: loggregator_tc
  type: certificate
  options:
    ca: loggregator_ca
    common_name: trafficcontroller
    extended_key_usage:
    - client_auth
    - server_auth
- name: loggregator_rlp
  type: certificate
  options:
    ca: loggregator_ca
    common_name: rlp
    alternative_names:
    - rlp
    - reverselogproxy
    extended_key_usage:
    - client_auth
    - server_auth
- name: loggregator_rlp_gateway
  type: certificate
  options:
    ca: loggregator_ca
    common_name: rlp_gateway
    extended_key_usage:
    - client_auth
- name: loggregator_agent
  type: certificate
  options:
    ca: loggregator_ca
    common_name: agent
    alternative_names:
    - metron
    - agent
    - localhost
    - 127.0.0.1
    - ip6-localhost
    extended_key_usage:
    - client_auth
    - server_auth
- name: logs_provider
  options:
    ca: loggregator_ca
    common_name: log-cache
    extended_key_usage:
    - client_auth
    - server_auth
  type: certificate
- name: log_cache_ca
  options:
    common_name: log-cache
    is_ca: true
  type: certificate
- name: log_cache
  options:
    alternative_names:
    - log_cache
    - log-cache
    - logcache
    ca: log_cache_ca
    common_name: log-cache
    extended_key_usage:
    - client_auth
    - server_auth
  type: certificate
- name: logcache_trafficcontroller
  options:
    ca: log_cache_ca
    common_name: trafficcontroller
    extended_key_usage:
    - client_auth
  type: certificate
- name: dns_api_tls_ca
  options:
    common_name: dnsApiTlsCa
    is_ca: true
  type: certificate
- name: dns_api_client_tls
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - client_auth
  type: certificate
- name: dns_api_server_tls
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - server_auth
  type: certificate
- name: dns_healthcheck_tls_ca
  type: certificate
  options:
    common_name: dnsHealthCheckTlsCa
    is_ca: true
- name: dns_healthcheck_server_tls
  type: certificate
  options:
    ca: dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth
- name: dns_healthcheck_client_tls
  type: certificate
  options:
    ca: dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
